name: Manage PRs

on:
  # pull_request_target trigger is used instead of pull_request so the token will have the write permissions needed to comment and merge.
  # Note that this means the version of the workflow from the PR base ref will be used as opposed to the head ref, as is the case with pull_request triggered workflows.
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - synchronize
  issue_comment:
    types:
      - created
      - edited

jobs:
  enabled:
    if: >
      github.event_name == 'pull_request_target' ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request != '' &&
        github.event.issue.state == 'open' &&
        contains(github.event.comment.body, 'ArduinoBot')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Hax
        run: echo "HACKED" >> hacked.md

      - name: Push
        uses: |
          git commit -m "hacked"
          git push
